### ISSUE TITLE
Visual Studio 2019 - Extension - None of the functions are working

### ISSUE THREAD

**Issue by laurin1** [gitextensions/gitextensions.vsix#16]
I have not worked in VS in a while. When I opened it up today, none of the GitEx functions are working - not from the toolbar menu, not from the right-click menus, nothing. No error or messages, just nothing happens. Uninstalled and reinstalled the GitEx extension, but still does not work.

Microsoft Visual Studio Community 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Community
Visual C++ 2019   00435-60000-00000-AA004
Microsoft Visual C++ 2019

**Comment by gerhardol** [comment]
What version of the extension is installed?
The VSIX plugin is handled in a separate Git repo

**Comment by mstv** [comment]
I have updated to MSVS Community 2019 16.8.4 recently, too.
(I have not used the GE VSIX plug-in actively. So I am not sure whether it was integrated before. But I remember to have seen the active branch in the status bar. Though it might have been displayed by a generic git functionality of MSVS.)
I installed "Git Extensions" using the Extensions Manager of MSVS and it works.

The taskbar has not changed:
![grafik](https://user-images.githubusercontent.com/36601201/105636272-ea458880-5e67-11eb-933a-353f22193922.png)
(This is OK for me because I do not want MSVS to run additional git commands.)

**Comment by laurin1** [comment]
> What version of the extension is installed?
![image](https://user-images.githubusercontent.com/75857/105636624-9cf8f500-5e2e-11eb-8386-3f7c51649f37.png)


> The VSIX plugin is handled in a separate Git repo
I thought so as well, but then why is this repo on the Marketplace page? 
https://marketplace.visualstudio.com/items?itemName=HenkWesthuis.GitExtensions
![image](https://user-images.githubusercontent.com/75857/105636516-60c59480-5e2e-11eb-92f4-24f71725d7dc.png)

**Comment by RussKie** [comment]
Please uninstall 33.33 version and install 3.4.0 version.

Somehow we uploaded a dev version to the store. Henk was working on getting
the wrong version pulled and replaced with the correct version.

**Comment by laurin1** [comment]
Done, but that did not fix the issue. Still, nothing happens with any of the functions.

![image](https://user-images.githubusercontent.com/75857/105738613-d435d780-5efc-11eb-9a87-eb4019757cfd.png)

Should I create this issue in https://github.com/gitextensions/gitextensions.vsix?

**Comment by laurin1** [comment]
This is working now.

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.32.0.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4360.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
Thank you for the update, @laurin1.
